str1=str.upper("prem ")
print(str1)
str2=str.lower("GAVALI")
print(str2)
str3=str.title("welcome to sunbeam")
print(str3)
str4=str.capitalize("welcome to sunbeam")
print(str4)
str5=str.swapcase("Hi Guys My Name Is Prem ")
print(str5)